[package]
name = "avalon"
version = "0.1.0"
authors = ["sunho <ksunhokim123@naver.com>"]

[dependencies]

simplelog = "^0.5.0"
log = "0.4"
uuid = { version = "0.7", features = ["v4"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
quick-error = "1.2.2"