version: 0.2

phases:
  build:
    commands:
      - go mod download
      - go build
  
artifacts:
  files:
    - appspec.yml
    - deploy.sh
    - ./lobby
  discard-paths: yes

cache:
  paths:
    - '/go/pkg/mod'