version: '3'
services:
  lobby:
    image: "ksunhokim/minda-lobby"
    ports:
    - "8080:8080"
    volumes:
    - ./configs:/home
    depends_on:
    - redis
    restart: always
  redis:
    image: "redis"
    expose:
     - 6379
  game:
    image: "ksunhokim/minda-game"
    depends_on:
    - redis
    ports:
    - "5353:5353"
    environment:
    - RUST_BACKTRACE=full
    command: ["/minda/target/release/game", "0.0.0.0:5353", "127.0.0.1:5353", "redis://redis/"]
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
  s3:
    image: minio/minio
    volumes:
      - s3data:/data
      - ./configs/s3:/root/.minio
    ports:
      - "9199:9000"
    expose:
      - 9000
    command: server /data
volumes:
  dbdata:
  s3data:
