auth:
  secret: "1234547890122412"
  debug: true
db:
  environment: development
s3:
  endpoint: s3:9000
  key: 36J9X8EZI4KEV1G7EHXA
  secret: ECk2uqOoNqvtJIMQ3WYugvmNPL_-zm3WcRqP5vUM
  region: ap-southeast-2
  bucket: minda
  external_name: localhost:9199
redis:
  addr: redis:6379
  max_idle: 120
